package ru.rt.nri.networkcapability;

import javax.xml.ws.WebFault;
import ru.rt.oms.TFault;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "Fault", targetNamespace = "http://oms.rt.ru/")
public class Fault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private TFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public Fault(String message, TFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public Fault(String message, TFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ru.rt.oms.TFault
     */
    public TFault getFaultInfo() {
        return faultInfo;
    }

}
