package ru.rt.nri.networkcapability;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NetworkCapabilityApi", targetNamespace = "http://nri.rt.ru/NetworkCapability")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ru.rt.nri.networkcapability.ObjectFactory.class,
    ru.rt.oms.ObjectFactory.class,
    ru.rt.nri.ObjectFactory.class
})
public interface NetworkCapabilityApi {


    /**
     * 
     * @param checkAccessCapabilityRequest
     * @return
     *     returns ru.rt.nri.networkcapability.CheckAccessCapabilityResponse
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "checkAccessCapabilityResponse", targetNamespace = "http://nri.rt.ru/NetworkCapability", partName = "checkAccessCapabilityResponse")
    public CheckAccessCapabilityResponse checkAccessCapability(
        @WebParam(name = "checkAccessCapabilityRequest", targetNamespace = "http://nri.rt.ru/NetworkCapability", partName = "checkAccessCapabilityRequest")
        CheckAccessCapabilityRequest checkAccessCapabilityRequest)
        throws Fault
    ;

}
